#!/bin/sh
#CFLAGS="-O3 -fno-strict-aliasing -g -Wall" ./configure --prefix=/usr --disable-debug --disable-epm --disable-shared
CFLAGS="-O3 -g -Wall -lrt" ./configure --prefix=/usr --disable-debug --disable-epm --disable-shared
