"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"module\teelbil;\n"
"export import \"eelbil_c\";\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"static _eel_version = [__version(0), __version(1), __version(2)];\n"
"if __version(3)\n"
"\t_eel_version[3] = __version(3);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"static _lib_version = [0, 3, 7];\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"export function eel_version\n"
"{\n"
"\treturn _eel_version;\n"
"}\n"
"\n"
"export function eelbil_version\n"
"{\n"
"\treturn _lib_version;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"export function exception_info(x)\n"
"{\n"
"\tlocal r = table [];\n"
"\tr.code = x;\n"
"\ttry\n"
"\t\tr.name = exception_name(x);\n"
"\texcept\n"
"\t\tr.name = \"\";\n"
"\n"
"\n"
"\n"
"\t\tr.description = \"(No description available.)\";\n"
"\treturn r;\n"
"}\n"
"\n"
"try\n"
"\tfor local x = 0, 99999\n"
"\t\t__exports()[exception_name((integer)x)] = (integer)x;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"export function deepclone(src)[_level]\n"
"{\n"
"\tif specified _level\n"
"\t\tlocal level = _level + 1;\n"
"\telse\n"
"\t\tlevel = 0;\n"
"\tif level > 1000\n"
"\t\tthrow \"deepclone(): Infinite recursion aborted!\";\n"
"\tswitch typeof src\n"
"\t  case array\n"
"\t  {\n"
"\t\tlocal a = [];\n"
"\t\tfor local i = 0, sizeof src - 1\n"
"\t\t\ta[i] = deepclone(src[i], level);\n"
"\t\treturn a;\n"
"\t  }\n"
"\t  case table\n"
"\t  {\n"
"\t\tlocal t = table [];\n"
"\t\tfor local i = 0, sizeof src - 1\n"
"\t\t\tt[key(src, i)] = deepclone(index(src, i), level);\n"
"\t\treturn t;\n"
"\t  }\n"
"\t  default\n"
"\t\treturn clone src;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"export function deepcompare(l, r)[_level]\n"
"{\n"
"\tif specified _level\n"
"\t\tlocal level = _level + 1;\n"
"\telse\n"
"\t\tlevel = 0;\n"
"\tif level > 1000\n"
"\t\tthrow \"deepcompare(): Infinite recursion aborted!\";\n"
"\tswitch typeof l\n"
"\t  case array\n"
"\t  {\n"
"\t\tif typeof r != array\n"
"\t\t\treturn false;\n"
"\t\tif sizeof l != sizeof r\n"
"\t\t\treturn false;\n"
"\t\tfor local i = 0, sizeof l - 1\n"
"\t\t\tif not deepcompare(l[i], r[i], level)\n"
"\t\t\t\treturn false;\n"
"\t\treturn true;\n"
"\t  }\n"
"\t  case table\n"
"\t  {\n"
"\t\tif typeof r != table\n"
"\t\t\treturn false;\n"
"\t\tif sizeof l != sizeof r\n"
"\t\t\treturn false;\n"
"\t\tfor local i = 0, sizeof l - 1\n"
"\t\t{\n"
"\t\t\tlocal k = key(l, i);\n"
"\t\t\tif not deepcompare(l[k], r[k], level)\n"
"\t\t\t\treturn false;\n"
"\t\t}\n"
"\t\treturn true;\n"
"\t  }\n"
"\t  default\n"
"\t\treturn l == r;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"$.cleanup = [];\n"
"\n"
"export procedure __cleanup\n"
"{\n"
"\tfor local i = 0, sizeof $.cleanup - 1\n"
"\t\t$.cleanup[i]();\n"
"\tdelete($);\n"
"}\n"
